name: Phrase pull translations
description: Pull translations from Phrase and commit them to the repository
branding: { color: blue, icon: box }
inputs:
  working_directory:
    { description: Working directory, required: false, default: "." }
runs:
  using: composite
  steps:
    # Checkout the repository
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - run: git config user.name "${{github.actor}}"
      shell: bash
    - run: git config user.email "${{github.actor}}@users.noreply.github.com"
      shell: bash

    # Remove all translations from src/locale/translations
    - name: Remove translations
      shell: bash
      working-directory: ${{inputs.working_directory}}
      run: rm -rf src/locale/translations/*.json

    # Download translations from Phrase
    - name: Download translations
      working-directory: ${{inputs.working_directory}}
      shell: bash
      run: npx -y phrase-cli pull

    # Commit and push changes
    - name: Commit and push changes
      working-directory: ${{inputs.working_directory}}
      shell: bash
      run: |
        git add src/locale/translations
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "feat(Translations): update translations (action)"
          git push origin HEAD --follow-tags
        fi
